services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    command: sh -c "npm run start"
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build: ./docker/backend
    volumes:
      - ./docker/backend/php.ini:/usr/local/php/php.ini
      - ./backend:/var/www/html

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./src:/usr/share/nginx/html

  database:
    container_name: database
    build: ./docker/database
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
